;/*FB_PKG_DELIM*/

__d("CometFeedHairlineMenuItem_storyMenuItem$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"CometFeedHairlineMenuItem_storyMenuItem$normalization",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}]};e.exports=a}),null);
__d("CometFeedHairlineMenuItem_storyMenuItem.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometFeedHairlineMenuItem_storyMenuItem",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],type:"HairlineMenuItem",abstractKey:null};e.exports=a}),null);
__d("CometFeedHairlineMenuItem.react",["CometFeedHairlineMenuItem_storyMenuItem.graphql","CometMenuSeparator.react","CometRelay","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react");function a(a,e){e=a.storyMenuItem;d("CometRelay").useFragment(h!==void 0?h:h=b("CometFeedHairlineMenuItem_storyMenuItem.graphql"),e);return j.jsx(c("CometMenuSeparator.react"),{})}a.displayName=a.name+" [from "+f.id+"]";e=j.forwardRef(a);g["default"]=e}),98);
__d("CometFeedStoryMenuOriginalStoryIDContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(null);g["default"]=b}),98);
__d("CometVideoToolsLoggingContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({composerEntryPoint:null,dialogMode:null});g["default"]=b}),98);
__d("copiedLinkPushToast",["fbt","ix","TetraIcon.react","cometPushToast","fbicon","react"],(function(a,b,c,d,e,f,g,h,i){"use strict";var j,k=j||d("react");function a(){d("cometPushToast").cometPushToast({icon:k.jsx(c("TetraIcon.react"),{color:"positive",icon:d("fbicon")._(i("498146"),20),size:20}),message:h._("Lien copi\u00e9"),testid:"CometCopyLinkToast"},void 0)}g["default"]=a}),98);
__d("CometVideoHomeMenuContentsContext.react",["emptyFunction","react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({enableLogging:!0,hideableToken:null,identifierToken:null,onHideVideo:c("emptyFunction"),onUnsaveVideo:c("emptyFunction"),tracking:null,videoChannelType:null});g["default"]=b}),98);/*FB_PKG_DELIM*/
__d("CometNewsfeedKeyCommandWidget",["createKeyCommandWidget"],(function(a,b,c,d,e,f,g){"use strict";a=c("createKeyCommandWidget")();g["default"]=a}),98);
__d("CometFeedStoryDropdownMenuLoggerContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext({nodeID:null});g["default"]=b}),98);
__d("CometMediaViewerRightRailUFIGlimmer.react",["CometGlimmer.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react"),j={ufi:{display:"x78zum5",justifyContent:"x1l1ennw",paddingTop:"xyamay9",paddingEnd:"x1pi30zi",paddingBottom:"x1l90r2v",paddingStart:"x1swvt13",$$css:!0},ufiGlimmer:{borderTopStartRadius:"x8u2fvd",borderTopEndRadius:"x1ht7hnu",borderBottomEndRadius:"x1quq95r",borderBottomStartRadius:"x5yzy4c",height:"x170jfvy",width:"xge0ay3",$$css:!0}};function a(){return i.jsxs("div",{className:"x78zum5 x1l1ennw xyamay9 x1pi30zi x1l90r2v x1swvt13",children:[i.jsx(c("CometGlimmer.react"),{index:1,xstyle:j.ufiGlimmer}),i.jsx(c("CometGlimmer.react"),{index:2,xstyle:j.ufiGlimmer}),i.jsx(c("CometGlimmer.react"),{index:3,xstyle:j.ufiGlimmer})]})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);